name: Fix Code style issues

on: [ push ]

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.0.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          skip_fetch: true
          commit_message: Fix styling 💅